package com.example.interfaces.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.colorResource
import com.example.interfaces.R


val md_theme_light_primary = Color(0xFF1860A5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD3E3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001C39)
val md_theme_light_secondary = Color(0xFF545F71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD8E3F8)
val md_theme_light_onSecondaryContainer = Color(0xFF111C2B)
val md_theme_light_tertiary = Color(0xFF6D5677)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF6D9FF)
val md_theme_light_onTertiaryContainer = Color(0xFF261430)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDFE2EB)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF73777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFFA3C9FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF1860A5)
val md_theme_light_outlineVariant = Color(0xFFC3C6CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFA3C9FF)
val md_theme_dark_onPrimary = Color(0xFF00315C)
val md_theme_dark_primaryContainer = Color(0xFF004883)
val md_theme_dark_onPrimaryContainer = Color(0xFFD3E3FF)
val md_theme_dark_secondary = Color(0xFFBCC7DB)
val md_theme_dark_onSecondary = Color(0xFF263141)
val md_theme_dark_secondaryContainer = Color(0xFF3C4758)
val md_theme_dark_onSecondaryContainer = Color(0xFFD8E3F8)
val md_theme_dark_tertiary = Color(0xFFD9BDE3)
val md_theme_dark_onTertiary = Color(0xFF3D2946)
val md_theme_dark_tertiaryContainer = Color(0xFF543F5E)
val md_theme_dark_onTertiaryContainer = Color(0xFFF6D9FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE3E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE3E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C6CF)
val md_theme_dark_outline = Color(0xFF8D9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE3E2E6)
val md_theme_dark_inversePrimary = Color(0xFF1860A5)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA3C9FF)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF5A82B7)
val CustomColor1 = Color(0xFFEDBBEA)
val CustomColor2 = Color(0xFF13E6B7)
val CustomColor3 = Color(0xFF8652EA)
val CustomColor4 = Color(0xFFAFADBF)
val light_CustomColor1 = Color(0xFF87458A)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFFFD6FB)
val light_onCustomColor1Container = Color(0xFF36003D)
val dark_CustomColor1 = Color(0xFFFAACF9)
val dark_onCustomColor1 = Color(0xFF521458)
val dark_CustomColor1Container = Color(0xFF6C2D71)
val dark_onCustomColor1Container = Color(0xFFFFD6FB)
val light_CustomColor2 = Color(0xFF006B54)
val light_onCustomColor2 = Color(0xFFFFFFFF)
val light_CustomColor2Container = Color(0xFF45FECD)
val light_onCustomColor2Container = Color(0xFF002117)
val dark_CustomColor2 = Color(0xFF00E0B2)
val dark_onCustomColor2 = Color(0xFF00382A)
val dark_CustomColor2Container = Color(0xFF00513F)
val dark_onCustomColor2Container = Color(0xFF45FECD)
val light_CustomColor3 = Color(0xFF713AD4)
val light_onCustomColor3 = Color(0xFFFFFFFF)
val light_CustomColor3Container = Color(0xFFEADDFF)
val light_onCustomColor3Container = Color(0xFF25005A)
val dark_CustomColor3 = Color(0xFFD2BBFF)
val dark_onCustomColor3 = Color(0xFF3E008E)
val dark_CustomColor3Container = Color(0xFF5816BB)
val dark_onCustomColor3Container = Color(0xFFEADDFF)
val light_CustomColor4 = Color(0xFF5455A9)
val light_onCustomColor4 = Color(0xFFFFFFFF)
val light_CustomColor4Container = Color(0xFFE1DFFF)
val light_onCustomColor4Container = Color(0xFF0D0664)
val dark_CustomColor4 = Color(0xFFC1C1FF)
val dark_onCustomColor4 = Color(0xFF252477)
val dark_CustomColor4Container = Color(0xFF3C3D8F)
val dark_onCustomColor4Container = Color(0xFFE1DFFF)

/*
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)


val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)*/